travis:
  secure:
    BINSTAR_TOKEN: E8vuGzC3N7Rp3GOwtgrQvi0A7yvRXMRncYHAY1HzWqgY2Zhh246TQJuEPSdiE+44q2LBVJfKL2cqbm3qD1cvDcyBY2/XIkSlY8vVUJlS1qLRhrbPtVECFu+dsMOzHY6dM+sWxsPPBgFTiZKcgXogtmd3qHWPG9LF4ECEeOTbEBsAXjXTiGnqLAYq4PFkC+RZamZYYyYYl9W0rBT9vHjz1onNCgIwZL8JANIOOY0OB+XUg/00mLCiTnE4z5TjiYmm2hh5TPDYDMJ06e+bmfNS5/c9uHiy62NcdKW93XhEcn0Ep7CRn/FpheZ5BC3jJ3C4JJa7TldsjfAjN0KBg5k+T+AsW2POg5VLanxEecy2QnDtrLzkU+AKegTcLqd8KbFY8mzPrkxew4M2HIY4PXACuavCOaFSsouiqxR1TDmllYy/0LGl6gVvoK/7qL6adCfPRndi/NzLHC+PsjX+vFn6KyyrAcmVEOu3iJNKN3h+aX6MlBAAXhcnn2XUUVwp0YktLpEZd5aWuoWeqD2qjX0qsSKMBIXmmVwSdVhL6TkXZcCCPwbUIVNFtge3J9gB+FwyaVx3lvbILbRuO5zC1pExprpkNY8at54SPMmlJbSb7MCv+rY3F765RtwxPs4sPnIgUphEvw0bscgM4Up5NP4eCwe/XgJXj9T3YOgX0ATTRsA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
